export const SHEET_SCHEMAS = {
  Roles: [
    "Date Found",
    "Company",
    "Role Title",
    "Level",
    "Status",
    "Notes",
    "Final Bucket",
    "Agent Score",
    "Manual Score Override",
    "Fit Score",
    "Financial Upside Score",
    "Compensation Score",
    "Scope Score",
    "Prestige Score",
    "Access Score",
    "Score Rationale",
    "Last Updated",
    "Source",
  ],
  Companies: [
    "Company",
    "Website",
    "Category",
    "Stage",
    "Funding Raised",
    "Last Round",
    "Last Round Date",
    "Estimated Valuation",
    "Top Investors",
    "Headcount",
    "Headcount Growth",
    "Revenue Model",
    "Financial Upside Thesis",
    "5x/10x Probability",
    "Compensation Potential",
    "Prestige Signal",
    "Risk Notes",
    "Target Priority",
    "Sources",
    "Last Researched",
  ],
  Contacts: [
    "Name",
    "Current Company",
    "Title",
    "Email",
    "LinkedIn URL",
    "Connection Degree",
    "Source",
    "Relationship Strength",
    "Target Company",
    "Can Refer",
    "Last Contacted",
    "Status",
    "Notes",
  ],
  "Warm Paths": [
    "Company",
    "Role Title",
    "Contact Name",
    "Connection Type",
    "Path Strength",
    "Mutual Connection",
    "Recommended Ask",
    "Status",
    "email",
    "LinkedIn URL",
    "Headline",
    "Location",
    "Source",
    "Notes",
  ],
  Interactions: ["Date", "Company", "Role Title", "Person", "Channel", "Outcome", "Notes", "Next Step"],
  "Interview Prep": [
    "Company",
    "Role Title",
    "Stage",
    "Likely Questions",
    "Company Thesis",
    "Product Opportunities",
    "Stories to Use",
    "Weak Spots",
    "Notes",
  ],
} as const;

export type SheetName = keyof typeof SHEET_SCHEMAS;

export const WORKBOOK_MANAGED_SHEETS = ["Roles", "Companies", "Interview Prep"] as const satisfies readonly SheetName[];

export const PROTECTED_USER_SHEETS = ["Contacts", "Warm Paths", "Interactions"] as const satisfies readonly SheetName[];

export const MACHINE_OWNED_ROLE_COLUMNS = [
  "Role Title",
  "Final Bucket",
  "Agent Score",
  "Fit Score",
  "Financial Upside Score",
  "Compensation Score",
  "Scope Score",
  "Prestige Score",
  "Score Rationale",
  "Last Updated",
  "Source",
] as const;
